Models/Entities/Article.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using De01_Enews.Models.enums;

namespace De01_Enews.Models.Entities;

public class Article
{
    [Key]
    public int Id { get; set; }
    
    [Required]
    [Display(Name = "Category")]
    public int CategoryId { get; set; }
    
    [Required]
    public string Title { get; set; }
    
    [Required]
    [DataType(DataType.Html)]
    public string Content { get; set; }
    
    [Required]
    public string Summary { get; set; }

    [Required]
    [EnumDataType(typeof(ArticleStatus))]
    public ArticleStatus Status { get; set; }
    
    [Required]
    [DataType(DataType.DateTime)]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy H:mm:ss zzz}", ApplyFormatInEditMode = true)]
    public DateTime PostedAt { get; set; }
    
    
    public virtual List<Image> Images { get; set; }
    
    [ForeignKey("CategoryId")]
    public virtual Category Category { get; set; }
}

Models/Entities/Category.cs
using System.ComponentModel.DataAnnotations;

namespace De01_Enews.Models.Entities;

public class Category
{
    [Key]
    public int Id { get; set; }
    
    public int Name { get; set; }
}

Models/Entities/Image.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace De01_Enews.Models.Entities;

public class Image
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }
    
    public string Path { get; set; }
    
    [Required]
    [Display(Name = "Article")]
    public int ArticleId { get; set; }

    [ForeignKey("ArticleId")]
    public virtual Article Article { get; set; }
}

Models/Entities/Role.cs
using System.ComponentModel.DataAnnotations;

namespace De01_Enews.Models.Entities;

public class Role
{
    [Key] public int Id { get; set; }

    public string Name { get; set; }

    public virtual List<User> Users { get; set; }
}

Models/Entities/User.cs
using System.ComponentModel.DataAnnotations;

namespace De01_Enews.Models.Entities;

public class User
{
    [Key] public int Id { get; set; }

    public string Username { get; set; }

    public string FullName { get; set; }
    
    public string Password { get; set; }
    
    public string Phone { get; set; }
    
    public string Email { get; set; }

    public int RoleId { get; set; }

    
    public virtual Role Role { get; set; }
}

Models/ErrorViewModel.cs
namespace De01_Enews.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ViewModels/LoginVm.cs
namespace De01_Enews.Models.ViewModels;

public class LoginVm
{
    public string Username { get; set; }

    public string Password { get; set; }
}

Models/ViewModels/RegisterVm.cs
namespace De01_Enews.Models.ViewModels;

public class RegisterVm
{
    public string Username { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }
    
    public string RetypePassword { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }
}

Models/enums/ArticleStatus.cs
namespace De01_Enews.Models.enums;

public enum ArticleStatus
{
    Pending,
    Approved,
    Disapproved
}

Controllers/AuthController.cs
using System.Security.Claims;
using De01_Enews.Models.Entities;
using De01_Enews.Models.ViewModels;
using De01_Enews.Repository;
using De01_Enews.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace De01_Enews.Controllers;

public class AuthController : Controller
{
    private readonly UnitOfWork _unit = new();

    public IActionResult Login()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Register()
    {
        return View();
    }

    [HttpPost]
    public async Task Authenticate(User user)
    {
        var claims = new List<Claim>
        {
            new(ClaimsIdentity.DefaultNameClaimType, user.Username),
            new(ClaimsIdentity.DefaultRoleClaimType, user.Role.Name)
        };
        ClaimsIdentity id = new(
            claims, "ApplicationCookie",
            ClaimsIdentity.DefaultNameClaimType,
            ClaimsIdentity.DefaultRoleClaimType
        );
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
    }

    [HttpPost]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        return RedirectToAction("Index", "Home");
    }

    [HttpPost]
    public async Task<IActionResult> Register(RegisterVm model)
    {
        if (!ModelState.IsValid) return View(model);

        if (model.Password != model.RetypePassword)
        {
            ModelState.AddModelError("", "Nhập lại mật khẩu không chính xác!");
            return View(model);
        }


        var user = _unit.UserRepository.Get(x => x.Username == model.Username).FirstOrDefault();
        if (user == null)
        {
            user = new User
            {
                FullName = model.FullName,
                Phone = model.Phone,
                Email = model.Email,
                Password = PasswordConverter.Hash(model.Password),
            };
            var userRole = _unit.RoleRepository.Get(x => x.Id == 2).FirstOrDefault();
            if (userRole != null) user.Role = userRole;

            _unit.UserRepository.Insert(user);
            _unit.Save();

            await Authenticate(user);
            return RedirectToAction("Index", "Home");
        }

        ModelState.AddModelError("", "The same account already exist");
        return View(model);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using De01_Enews.Models;

namespace De01_Enews.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace De01_Enews.Controllers;

public class UserController : Controller
{
    public IActionResult Info()
    {
        return View();
    }
}

Pages/User/Info.cshtml
@model dynamic

@{
    ViewBag.Title = "User's Info";
    Layout = "_Layout";
}

<h2>User's Info</h2>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Enews</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/De01_Enews.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Enews</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>

            <div class="ms-auto">
                @if (User.Identity is { IsAuthenticated: true })
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Info">
                                Hello, <span class="text-primary">@User.Identity.Name</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Logout</a>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Enews by chinhpc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>